=== RomRaider/original.flat/trunk/profile.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT parameter EMPTY >
<!ATTLIST parameter id ID #REQUIRED >

<!ELEMENT parameters ( parameter+ ) >

<!ELEMENT switch EMPTY >
<!ATTLIST switch id ID #REQUIRED >

<!ELEMENT switches ( switch+ ) >

<!ELEMENT profile ( parameters*, switches* ) >

=== RomRaider/original.flat/trunk/profile.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE profile SYSTEM "profile.dtd">

<profile>

    <parameters>
        <parameter id="P1"/>
        <parameter id="P2"/>
        <parameter id="P3"/>
        <parameter id="P4"/>
        <parameter id="P5"/>
        <parameter id="P6"/>
        <parameter id="P7"/>
        <parameter id="P8"/>
        <parameter id="P9"/>
        <parameter id="P10"/>
        <parameter id="P11"/>
        <parameter id="P12"/>
        <parameter id="P13"/>
        <parameter id="P14"/>
        <parameter id="P15"/>
        <parameter id="P16"/>
        <parameter id="P17"/>
        <parameter id="P18"/>
        <parameter id="P19"/>
        <parameter id="P20"/>
        <parameter id="P21"/>
        <parameter id="P22"/>
        <parameter id="P23"/>
        <parameter id="P24"/>
        <parameter id="P25"/>
        <parameter id="P26"/>
        <parameter id="P27"/>
        <parameter id="P28"/>
        <parameter id="P29"/>
        <parameter id="P30"/>
        <parameter id="P31"/>
        <parameter id="P32"/>
        <parameter id="P33"/>
        <parameter id="P34"/>
        <parameter id="P35"/>
        <parameter id="P36"/>
        <parameter id="P37"/>
        <parameter id="P38"/>
        <parameter id="P39"/>
        <parameter id="P40"/>
        <parameter id="P41"/>
        <parameter id="P42"/>
        <parameter id="P43"/>
        <parameter id="P44"/>
        <parameter id="P45"/>
        <parameter id="P46"/>
        <parameter id="P47"/>
        <parameter id="P48"/>
        <parameter id="P49"/>
        <parameter id="P50"/>
        <parameter id="P51"/>
        <parameter id="P52"/>
        <parameter id="P53"/>
        <parameter id="P54"/>
        <parameter id="P55"/>
        <parameter id="P56"/>
        <parameter id="P57"/>
        <parameter id="P58"/>
        <parameter id="P59"/>
        <parameter id="P60"/>
        <parameter id="P61"/>
        <parameter id="P62"/>
        <parameter id="P63"/>
        <parameter id="P64"/>
        <parameter id="P65"/>
        <parameter id="P66"/>
        <parameter id="P67"/>
        <parameter id="P68"/>
        <parameter id="P69"/>
        <parameter id="P70"/>
        <parameter id="P71"/>
        <parameter id="P72"/>
        <parameter id="P73"/>
        <parameter id="P74"/>
        <parameter id="P75"/>
        <parameter id="P76"/>
        <parameter id="P77"/>
        <parameter id="P78"/>
        <parameter id="P79"/>
        <parameter id="P80"/>
        <parameter id="P81"/>
        <parameter id="P82"/>
        <parameter id="P83"/>
        <parameter id="P84"/>
        <parameter id="P85"/>
        <parameter id="P86"/>
        <parameter id="P87"/>
        <parameter id="P88"/>
        <parameter id="P89"/>
        <parameter id="P90"/>
        <parameter id="P91"/>
    </parameters>

    <switches>
        <switch id="S1"/>
        <switch id="S2"/>
        <switch id="S3"/>
        <switch id="S4"/>
        <switch id="S5"/>
        <switch id="S6"/>
        <switch id="S7"/>
        <switch id="S8"/>
        <switch id="S9"/>
        <switch id="S10"/>
        <switch id="S11"/>
        <switch id="S12"/>
        <switch id="S13"/>
        <switch id="S14"/>
        <switch id="S15"/>
        <switch id="S16"/>
        <switch id="S17"/>
        <switch id="S18"/>
        <switch id="S19"/>
        <switch id="S20"/>
        <switch id="S21"/>
        <switch id="S22"/>
        <switch id="S23"/>
        <switch id="S24"/>
        <switch id="S25"/>
        <switch id="S26"/>
        <switch id="S27"/>
        <switch id="S28"/>
        <switch id="S29"/>
        <switch id="S30"/>
        <switch id="S31"/>
        <switch id="S32"/>
        <switch id="S33"/>
        <switch id="S34"/>
        <switch id="S35"/>
        <switch id="S36"/>
        <switch id="S37"/>
        <switch id="S38"/>
        <switch id="S39"/>
        <switch id="S40"/>
        <switch id="S41"/>
        <switch id="S42"/>
        <switch id="S43"/>
        <switch id="S44"/>
        <switch id="S45"/>
        <switch id="S46"/>
        <switch id="S47"/>
        <switch id="S48"/>
        <switch id="S49"/>
        <switch id="S50"/>
        <switch id="S51"/>
        <switch id="S52"/>
        <switch id="S53"/>
        <switch id="S54"/>
        <switch id="S55"/>
        <switch id="S56"/>
        <switch id="S57"/>
        <switch id="S58"/>
        <switch id="S59"/>
        <switch id="S60"/>
        <switch id="S61"/>
        <switch id="S62"/>
        <switch id="S63"/>
        <switch id="S64"/>
        <switch id="S65"/>
        <switch id="S66"/>
        <switch id="S67"/>
        <switch id="S68"/>
    </switches>

</profile>
